# Generated by Django 4.2.24 on 2025-09-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_disponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_financiar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuotas', models.PositiveIntegerField()),
                ('interes_anual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sistema', models.CharField(choices=[('FR', 'Francés (cuota fija)')], default='FR', max_length=2)),
                ('tasa_mensual', models.DecimalField(decimal_places=8, max_digits=10)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_intereses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
